# Generated by Django 5.0 on 2025-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_item_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='categories/videos/'),
        ),
    ]
