# Generated by Django 5.0 on 2025-01-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
