# Generated by Django 5.0 on 2025-02-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
